#print("Olá, Mundo!!!")
#print("Olá, Python!")
#print("A pequenina aranha escalou a tromba d'água.")
#print("Caiu a chuva e lavou a aranha.")
#print("A pequenina aranha escalou a tromba d'água.")
#print()
#print("Caiu a chuva e lavou a aranha.")
#print("A pequenina aranha\nsubiu a tromba d'água.")
#print()
#print("Caiu a chuva\ne lavou a aranha.")
#print("A pequenina aranha", "subiu", "a tromba d'água.")
#print("Meu nome é", "Python.")
#print("Monty Python.")
#print("Meu nome é", "Python.", end=" ")
#print("Monty Python.")
#print("Meu nome é", "Python.", end="")
#print("Monty Python.")
#print("Meu", "nome", "é", "Python.", sep="-")
#print("Meu", "nome", "é", sep="_", end="*")
#print("Monty", "Python.", sep="*", end="*\n")
#print("Programação","Essenciais","em")
#print("Python.")
#print("Programação","Essenciais","em", sep="***", end="...")
#print("Python.")
print("    *")
print("  *   *")
print(" *     *")
print("*       *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print()
print("    *\n  *   *\n *     *\n*       *\n***   ***\n  *   *\n  *   *\n  *****")
print()
print("        *")
print("      *   *")
print("     *     *")
print("    *       *")
print("   *         *")
print("  *           *")
print(" *             *")
print("*               *")
print("******     ******")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *     *")
print("     *******")
print()
print("    *\n  *   *\n *     *\n*       *\n***   ***\n  *   *\n  *   *\n  *****")
print()

